Place#new作成完了
atsss/cocchi-fe pull request #11
Opened 2020-10-22 05:34 UTC by yoshioooo

![image](https://user-images.githubusercontent.com/58821419/96829044-00b9ef00-13f6-11eb-8b47-1c4800d8bd29.png)

2020-10-22 05:38 UTC, atsss requested changes
やりなおし。

2020-10-22 05:38 UTC, atsss commented on src/config/Routes/index.tsx
> +    <Route exact path="/places/:id/new" component={PlacesNew} />
new はパラメーター要らない。
> https://railsguides.jp/routing.html#crud%E3%80%81%E5%8B%95%E8%A9%9E%E3%80%81%E3%82%A2%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3

2020-10-22 05:38 UTC, atsss commented on src/components/pages/places/New/index.tsx
> +  const place = places.find((element) => element.id === parseInt(id, 10))
id 要らない。

2020-10-22 05:38 UTC, atsss commented on src/components/templates/places/New/index.tsx
> +    <EditHeader backPath={`/places/${place.id}`}>新規ピン</EditHeader>
`places/id/edit` やな。

2020-11-05 06:24 UTC, atsss commented on src/components/pages/places/New/index.tsx
> +  return <Template place={places} />
`return <p>test</p>` したらどうなるの？

2020-11-05 06:28 UTC, atsss commented on src/config/Routes/index.tsx
> +    <Route exact path="/places/new" component={PlacesNew} />
この行を20行目の下に移動してみ。

2020-11-05 07:09 UTC, yoshioooo commented
![image](https://user-images.githubusercontent.com/58821419/98208827-9a5bc300-1f03-11eb-9f1c-0c9a935b8e17.png)

2020-11-05 18:40 UTC, atsss commented on src/components/pages/places/New/index.tsx
> +  }
要らない。

2020-11-05 18:43 UTC, atsss commented on src/components/pages/places/New/index.tsx
> +  return <Template place={places} />
template で使われるリソースはないので、引数を渡す必要はない

2020-11-05 18:44 UTC, atsss commented on src/components/templates/places/New/index.tsx
> +    <EditHeader backPath={`places/${place.id}/edit`}>新規ピン</EditHeader>
戻り先をとりあえず Communities#index にしておいて。後で、直前ページに戻るように俺が直す。

2020-11-06 04:18 UTC, yoshioooo commented
https://gyazo.com/d6e55a301273191e827770806dce0ee1

2020-11-06 04:21 UTC, atsss commented on src/components/pages/places/New/index.tsx
> +export const PlacesNew: React.FC = () => <Template place={places} />
place の引数は使ってないので要らない。

2020-11-06 05:15 UTC, atsss approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/105660)

2020-11-06 05:16 UTC, merged